<log>
  <uncaught_exception timestamp='2018-08-09-Thu-15.18.11.541' class='RuntimeError'>
    <message>
      Oops!
    </message>
    <backtrace>
      <![CDATA[
C:/Users/Burdette/Documents/GitHub/structured_log/readme_files/scripts/exception.rb:4:in `block in <main>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/structured_log-0.9.0/lib/structured_log.rb:48:in `open'
C:/Users/Burdette/Documents/GitHub/structured_log/readme_files/scripts/exception.rb:3:in `<main>'
]]>
    </backtrace>
  </uncaught_exception>
</log>
