<log>
  <section name='Section with rescue'>
    <uncaught_exception>
      <class>
        RuntimeError
      </class>
      <message>
        Boo!
      </message>
      <backtrace>
      </backtrace>
    </uncaught_exception>
  </section>
  <section name='Another section'>
    <comment>
      This section is ok.
    </comment>
  </section>
</log>
